version: '3'
services:
  li:
    container_name: removert_V2
    build: .
    network_mode: "host"
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    privileged: false     # used for displaying graphical tools, use with caution
    # 'xhost +local:docker' must be done in terminal outside of docker container
    environment:
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=/tmp/.docker.xauth
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      # - ROS_MASTER_URI=http://192.168.1.3:11311/
    volumes:
    # add C:/DATABASE:/home
      #- C:/REPOS/removert:/catkin_ws/src/removert
      - C:/DATABASE:/home/DATABASE
